# add this repo's ./src directory to FuseSoC's libraries
[library.src]
location = src
sync-uri = src
sync-type = local
auto-sync = true

[library.opentitan.git]
location = fusesoc_libraries/opentitan.git
sync-uri = https://github.com/lowRISC/opentitan.git
sync-type = git
auto-sync = true
# TODO lock version

[library.mocha.git]
location = fusesoc_libraries/mocha.git
sync-uri = https://github.com/lowRISC/mocha.git
sync-type = git
auto-sync = true
# TODO lock version

# TODO It's not good that we are pulling in Mocha just to use its AXI package
# The AXI cores come from Pulp, but have been modified in Mocha to use lowRISC primitives
# Unfortunately the modified version is version controlled with all of Mocha so we have to pull in the whole repo
# This is a bit of a performance hit and a bit inelegant but more importantly, it means reproducibility is a bit shaky
# FuseSoC expects the version number in the core to guarantee reproducibility, but there are two competing versions of
# the AXI package (pulp-platform.org::axi:0.39.9) with the same version number: the original and the lowRISC version
# Yet another reason why hashes are better than version numbers!
