// Copyright lowRISC contributors (COSMIC project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

/*
Module: ethernet_csr
Author: Thomas O'Dea <thomas.odea@lowrisc.org>

-------------------------------------------------------------------------------
    DESCRIPTION
-------------------------------------------------------------------------------
Control and status registers for the Ethernet IP.
See ethernet.rdl for a specification of registers.

-------------------------------------------------------------------------------
    TESTS
-------------------------------------------------------------------------------
There are no dedicated tests for this module but it is exercised by the
ethernet_top and ethernet_top_axi testbenches.

*/

`include "prim_assert.sv"

module ethernet_csr (
    input                                       clk_i,
    input                                       rst_ni,
    input  mem_if_utils_pkg::mem_req_t          mem_req_i,
    output mem_if_utils_pkg::mem_rsp_t          mem_rsp_o,
    output ethernet_pkg::mac_config_t           mac_config_o,
    input  ethernet_pkg::mac_status_t           mac_status_i,
    output ethernet_pkg::rx_config_t            rx_config_o,
    input  ethernet_pkg::rx_status_t            rx_status_i,
    output logic                                rx_pop_o,
    output ethernet_pkg::tx_config_t            tx_config_o,
    input  ethernet_pkg::tx_status_t            tx_status_i,
    input  ethernet_pkg::eth_rgmii_mdio_in_t    eth_rgmii_mdio_i,
    output ethernet_pkg::eth_rgmii_mdio_out_t   eth_rgmii_mdio_o,
    output logic                                tx_kick_o,
    output logic                                irq_o
);
    logic unused;
    assign unused = ^mac_status_i;

    // TODO this module could do with refactoring, it's pretty ugly and doesn't support strobing or writing 0/2 CSRs in the same transaction
    // also ideally should be autogenerated from the RDL

    // See ethernet.rdl for regmap. Addresses are:
    typedef enum logic [ethernet_pkg::CSR_ADDR_W-1:0] {
        REG_INTR_STATE_ADDR = 7'h00,
        REG_INTR_MASK_ADDR  = 7'h04,
        REG_INTR_TEST_ADDR  = 7'h08,
        REG_CTRL_ADDR       = 7'h10,
        REG_STATUS_ADDR     = 7'h14,
        REG_MACLO_ADDR      = 7'h18,
        REG_MACHI_ADDR      = 7'h1C,
        REG_TX_CTRL_ADDR    = 7'h20,
        REG_RX_POP_ADDR     = 7'h28,
        REG_MDIO_CTRL_ADDR  = 7'h2C,
        REG_VENDOR_ID_ADDR  = 7'h30,
        REG_DEVICE_ID_ADDR  = 7'h34,
        REG_MAGIC_NUM_ADDR  = 7'h38
    } reg_addr_e;

    //////////////////////////////////////
    // Memory-mapped register interface //
    //////////////////////////////////////
    reg_addr_e reg_addr;
    assign reg_addr = (reg_addr_e)'({mem_req_i.addr[ethernet_pkg::CSR_ADDR_W-1:3], (mem_req_i.be[0] ? 3'h0 : 3'h4)}); // if we are writing, ensure the address is aligned to the CSR actually being targetted by the byte-enable signal. It doesn't matter if we are reading
    logic bad_request,bad_addr;
    assign bad_addr = ~(
        (reg_addr == REG_INTR_STATE_ADDR        ) ||
        (reg_addr == REG_INTR_MASK_ADDR         ) ||
        (reg_addr == REG_INTR_TEST_ADDR         ) ||
        (reg_addr == REG_CTRL_ADDR              ) ||
        (reg_addr == REG_STATUS_ADDR            ) ||
        (reg_addr == REG_MACLO_ADDR             ) ||
        (reg_addr == REG_MACHI_ADDR             ) ||
        (reg_addr == REG_TX_CTRL_ADDR           ) ||
        (reg_addr == REG_RX_POP_ADDR            ) ||
        (reg_addr == REG_MDIO_CTRL_ADDR         ) ||
        (reg_addr == REG_VENDOR_ID_ADDR         ) ||
        (reg_addr == REG_DEVICE_ID_ADDR         ) ||
        (reg_addr == REG_MAGIC_NUM_ADDR         )
    );
    assign bad_request = (
        (bad_addr)                    || // access to undefined register
        (mem_req_i.addr[1:0] != 2'h0) || // unaligned access
        ((mem_req_i.be != 8'h0F) & (mem_req_i.be != 8'hF0) & (mem_req_i.we)) || // do not allow writing 0 or 2 CSRs simultaneously
        (mem_req_i.we && (reg_addr inside {REG_STATUS_ADDR,REG_VENDOR_ID_ADDR,REG_DEVICE_ID_ADDR,REG_MAGIC_NUM_ADDR})) // do not allow writes to read-only registers
    );
    assign mem_rsp_o.gnt = mem_req_i.req;

    logic write;
    assign write = mem_req_i.req && mem_req_i.we && !bad_request;

    logic [6:0] intr_mask;

    logic tx_done_sticky;
    logic manual_irq_sticky;
    logic packet_lost_sticky;

    logic loopback_mode;
    logic promiscuous_mode;
    logic [47:0] mac_addr;
    logic [10:0] tx_packet_len;

    logic mdio_clk;
    logic mdio_o;
    logic mdio_oen;

    ////////////////
    // Interrupts //
    ////////////////
    logic manual_irq_pulse;

    logic [6:0] interrupts;
    assign interrupts[6] =  manual_irq_pulse || manual_irq_sticky;
    assign interrupts[5] =  tx_status_i.done_pulse || tx_done_sticky;
    assign interrupts[4] =  rx_status_i.pkt_lost_pulse || packet_lost_sticky;
    assign interrupts[3] =  rx_status_i.buf_almost_full;
    assign interrupts[2] =  rx_status_i.table_full;
    assign interrupts[1] =  rx_status_i.table_almost_full;
    assign interrupts[0] = ~rx_status_i.empty; // RX buffer not empty

    // Three of the interrupts are event-triggered and sticky, with write-to-clear behaviour
    // They are implemented here
    always_ff @ (posedge clk_i or negedge rst_ni) begin
        if (!rst_ni) begin
            tx_done_sticky                                  <= 1'b0;
            manual_irq_sticky                               <= 1'b0;
            packet_lost_sticky                              <= 1'b0;
        end else begin
            // Clear sticky bits when the interrupt is acknowledged by software
            if (write && (reg_addr == REG_INTR_STATE_ADDR)) begin
                if (mem_req_i.data[4]) packet_lost_sticky   <= 1'b0;
                if (mem_req_i.data[5]) tx_done_sticky       <= 1'b0;
                if (mem_req_i.data[6]) manual_irq_sticky    <= 1'b0;
            end else begin
                // Set sticky bits when the corresponding interrupt condition is met
                if (interrupts[4]) packet_lost_sticky       <= 1'b1;
                if (interrupts[5]) tx_done_sticky           <= 1'b1;
                if (interrupts[6]) manual_irq_sticky        <= 1'b1;
            end
            // note that you cannot clear RX status interrupts with a write - they must be serviced or masked
        end
    end

    /////////////////
    // Write logic //
    /////////////////

    // Register INTR_MASK
    always_ff @ (posedge clk_i or negedge rst_ni) begin
        if (!rst_ni)                                        intr_mask <= '0; // disable all interrupts after reset
        else if (write && (reg_addr == REG_INTR_MASK_ADDR)) intr_mask <= mem_req_i.data[32+6:32];
    end

    // Register INTR_TEST
    assign manual_irq_pulse = (write && (reg_addr == REG_INTR_TEST_ADDR) && mem_req_i.data[0]); // pulse an interrupt whenever 1 is written to this register

    // Register CTRL
    always_ff @ (posedge clk_i or negedge rst_ni) begin
        if (!rst_ni) begin
            promiscuous_mode    <= 1'b0;
            loopback_mode       <= 1'b0;
        end
        else if (write && (reg_addr == REG_CTRL_ADDR)) begin
            promiscuous_mode    <= mem_req_i.data[0];
            loopback_mode       <= mem_req_i.data[1];
        end
    end

    // Registers MACLO and MACHI
    always_ff @ (posedge clk_i or negedge rst_ni) begin
        if (!rst_ni)                                    mac_addr[47:0]  <= 48'h0;
        else if (write && (reg_addr == REG_MACLO_ADDR)) mac_addr[31:0]  <= mem_req_i.data[31:0]; // MACLO
        else if (write && (reg_addr == REG_MACHI_ADDR)) mac_addr[47:32] <= mem_req_i.data[47:32]; // MACHI
    end

    // Register TX_CTRL - note that side effect of kicking off a transmission
    always_ff @ (posedge clk_i or negedge rst_ni) begin
        if (!rst_ni)                                        tx_packet_len <= 11'h0;
        else if (write && (reg_addr == REG_TX_CTRL_ADDR))   tx_packet_len <= mem_req_i.data[10:0];
    end
    assign tx_kick_o = (write && (reg_addr == REG_TX_CTRL_ADDR) && (|mem_req_i.data[10:0])); // kick off a transmission whenever TX_CTRL is written with nonzero packet length
    // TODO reject writes to this register if another TX is already in progress

    // Register RX POP - write-only with side effect
    assign rx_pop_o = (write && (reg_addr == REG_RX_POP_ADDR) && mem_req_i.data[0]); // pop a packet from the RX buffer whenever 1 is written to this register

    // Register MDIO_CTRL - mix of read-only and read-write
    always_ff @ (posedge clk_i or negedge rst_ni) begin
        if (!rst_ni) begin
            mdio_clk  <= 1'b0;
            mdio_o    <= 1'b0;
            mdio_oen  <= 1'b0;
        end
        else if (write && (reg_addr == REG_MDIO_CTRL_ADDR)) begin
            mdio_clk  <= mem_req_i.data[32+0];
            mdio_o    <= mem_req_i.data[32+1];
            mdio_oen  <= mem_req_i.data[32+2];
        end
    end

    /////////////////
    // Device info //
    /////////////////
    // Make vendor ID, device ID, device version available as read-only field
    logic [31:0] vendor_id, device_id, magic_num;
    assign vendor_id = ethernet_pkg::VENDOR_ID;
    assign device_id = ethernet_pkg::DEVICE_ID;
    assign magic_num = ethernet_pkg::MAGIC_NUM; // random magic number to identify the build

    ////////////////
    // Read logic //
    ////////////////

    logic [31:0] status;
    assign status = {
        20'b0, // upper bits reserved
        rx_status_i.n_packets_in_rx_buf, // 4 bits status[11:8]
        tx_status_i.busy,
        3'b0, // reserved bits
        rx_status_i.buf_almost_full,
        rx_status_i.table_full,
        rx_status_i.table_almost_full,
        ~rx_status_i.empty // bit 0 : RX buffer not empty
    };

    logic [63:0] read_data;
    assign mem_rsp_o.data = read_data;

    // NOTE: because the data bus is 64 bits wide, we read two 32-bit registers at a time here
    always_ff @ (posedge clk_i or negedge rst_ni) begin
        if (!rst_ni) read_data <= '0;
        else begin
            unique case ({reg_addr[ethernet_pkg::CSR_ADDR_W-1:3],3'b0})
                (REG_INTR_STATE_ADDR)   : read_data <= {25'h0, intr_mask, 25'h0, interrupts};
                // REG_INTR_MASK_ADDR absorbed into the above
                (REG_INTR_TEST_ADDR)    : read_data <= '0;
                // reserved address here
                (REG_CTRL_ADDR)         : read_data <= {status, 30'h0, loopback_mode, promiscuous_mode};
                // REG_STATUS_ADDR absorbed into the above
                (REG_MACLO_ADDR)        : read_data <= {16'h0, mac_addr};
                // REG_MACHI_ADDR absorbed into the above
                (REG_TX_CTRL_ADDR)      : read_data <= {53'h0, tx_packet_len};
                // reserved address here
                (REG_RX_POP_ADDR)       : read_data <= {28'h0, eth_rgmii_mdio_i, mdio_oen, mdio_o, mdio_clk, 32'h0};
                // REG_MDIO_CTRL_ADDR absorbed into the above
                (REG_VENDOR_ID_ADDR)    : read_data <= {device_id, vendor_id};
                // REG_DEVICE_ID_ADDR absorbed into the above
                (REG_MAGIC_NUM_ADDR)    : read_data <= {32'h0, magic_num};
                // remaining addresses reserved
                default: read_data <= '0; // undefined registers read as zero
            endcase
        end
    end

    logic mem_rsp_o_err_q;
    always_ff @ (posedge clk_i or negedge rst_ni) begin
        if (!rst_ni) mem_rsp_o_err_q <= 1'b0;
        else         mem_rsp_o_err_q <= bad_request; // respond with an error if the request is invalid
    end // TODO detect writes to read-only registers
    assign mem_rsp_o.err = mem_rsp_o_err_q;

    ///////////////////////
    // Assign to outputs //
    ///////////////////////
    assign rx_config_o.mac_addr = mac_addr;
    assign rx_config_o.promiscuous_mode = promiscuous_mode;

    assign tx_config_o.packet_len = tx_packet_len;
    assign irq_o = |(intr_mask & interrupts); // interrupt output is the masked combination of all interrupt sources

    assign mac_config_o.loopback = loopback_mode;

    assign eth_rgmii_mdio_o.o = mdio_o;
    assign eth_rgmii_mdio_o.oen = mdio_oen;
    assign eth_rgmii_mdio_o.c = mdio_clk;

    ////////////////
    // Assertions //
    ////////////////
    // Assert that the memory interface behaves correctly
    mem_if_assertions u_mem_if_assertions (
        .clk_i,
        .rst_ni,
        .mem_req_i(mem_req_i),
        .mem_rsp_o(mem_rsp_o)
    );

    // Assert that the outputs are known
    `ASSERT_KNOWN(MacConfigOLoopback_A         , mac_config_o.loopback);
    `ASSERT_KNOWN(RxConfigOMacAddr_A           , rx_config_o.mac_addr);
    `ASSERT_KNOWN(RxConfigOPromiscuousMode_A   , rx_config_o.promiscuous_mode);
    `ASSERT_KNOWN(RxPopO_A                     , rx_pop_o);
    `ASSERT_KNOWN(TxConfigOPacketLen_A         , tx_config_o.packet_len);
    `ASSERT_KNOWN(TxKickO_A                    , tx_kick_o);
    `ASSERT_KNOWN(IrqO_A                       , irq_o);

    // Assert that tx_kick_o is a pulse
    `ASSERT_PULSE(CSR_TxKickPulseO_A, tx_kick_o);

    // Assert the values under reset
    `ASSERT(RstCfgLoopback_A,      !rst_ni |-> mac_config_o.loopback == 1'b0,                       clk_i, 0);
    `ASSERT(RstCfgPromiscuous_A,   !rst_ni |-> rx_config_o.promiscuous_mode == 1'b0,                clk_i, 0);
    `ASSERT(RstCfgMacAddr_A,       !rst_ni |-> rx_config_o.mac_addr == 48'h0,                       clk_i, 0);
    `ASSERT(RstCfgTxPacketLen_A,   !rst_ni |-> tx_config_o.packet_len == 11'h0,                     clk_i, 0);
    `ASSERT(RstCfgTxKick_A,        !rst_ni |-> tx_kick_o == 1'b0,                                   clk_i, 0);
    `ASSERT(RstCfgRxPop_A,         !rst_ni |-> rx_pop_o == 1'b0,                                    clk_i, 0);
    `ASSERT(RstCfgIrq_A,           !rst_ni |-> irq_o == 1'b0,                                       clk_i, 0);
    //                                                                                              ^ clk, ^ normally a reset to disable the assertion, but we want these to be true even under reset
endmodule
